# Generated by Django 5.1.3 on 2024-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_is_scribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
